### ISSUE TITLE
Release new version without gulp-util dep

### ISSUE THREAD

**Issue by joanjane** [hparra/gulp-spawn#18]
Hi, 
I've been using this [repo](https://github.com/nfroidure/gulp-iconfont) which uses this package and shows warnings about depending on gulp-util dependency of version 4.0.0.

I've seen that the code of this repo was updated 9 months ago (removing deprecated deps.), but the released version was 1 year ago.

Is it ready for a release to npm feed? Can you publish it?

Cheers

**Comment by pioug** [comment]
I recently got the publish permission on the npm package. I just bumped a _patch_ version: https://github.com/pioug/gulp-spawn/compare/v0.4.0...v0.4.1

**Comment by pioug** [comment]
Aaand I am reverting the gulp-util change. I didn't notice tests were failing and published the `v0.4.1` 🙈

![image](https://user-images.githubusercontent.com/3654180/46518154-6f768f00-c8a5-11e8-92ef-54f923d12f2e.png)

I don't know how serious was the issue but I prefer to revert while I am figuring out the issue. Apologies for any inconvenience caused 🙏
